<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="xml" indent="yes"/>

	<xsl:template match="/">



<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:camel="http://camel.apache.org/schema/spring"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

	<restContext id="autoGeneratedFromSpec" xmlns="http://camel.apache.org/schema/spring">

<!-- 	plugin generates path attribute in rest element
		we intentionally discard it as it conflicts with Camel's context path -->
		<xsl:for-each select="/camel:rests/camel:rest">
			<rest>
				<xsl:copy-of select="*"/>
			</rest>
		</xsl:for-each>
	</restContext>

</beans>



	</xsl:template>

</xsl:stylesheet>
