---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 18:43:39 +0000
    app.openshift.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
    app.quarkus.io/commit-id: 424d91e19764a167eeff37cc26d90fd50ec21110
    app.quarkus.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
  labels:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: end1
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 18:43:39 +0000
    app.openshift.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
    app.quarkus.io/commit-id: 424d91e19764a167eeff37cc26d90fd50ec21110
    app.quarkus.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
  labels:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: end1
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-java
spec:
  dockerImageRepository: fabric8/s2i-java
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 18:43:39 +0000
    app.openshift.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
    app.quarkus.io/commit-id: 424d91e19764a167eeff37cc26d90fd50ec21110
    app.quarkus.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
  labels:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: end1
spec:
  output:
    to:
      kind: ImageStreamTag
      name: end1:1.0.0
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java:2.3
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 18:43:39 +0000
    app.openshift.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
    app.quarkus.io/commit-id: 424d91e19764a167eeff37cc26d90fd50ec21110
    app.quarkus.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
  labels:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: end1
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: end1
    app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-10-21 - 18:43:39 +0000
        app.openshift.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
        app.quarkus.io/commit-id: 424d91e19764a167eeff37cc26d90fd50ec21110
        app.quarkus.io/vcs-url: https://github.com/redhat-integration-resources/camel-sizing-patterns.git
      labels:
        app.kubernetes.io/name: end1
        app.kubernetes.io/version: 1.0.0
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/end1-1.0.0-runner.jar
        image: bruno/end1:1.0.0
        imagePullPolicy: IfNotPresent
        name: end1
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - end1
      from:
        kind: ImageStreamTag
        name: end1:1.0.0
    type: ImageChange
